spring:
  aop:
    proxy-target-class: true
  profiles:
    active:
    - dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:      
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 3000000
      max-evictable-idle-time-millis: 3000000
      #min-evictable-idle-time-millis: 3600000
      validation-query: SELECT 1
      validation-query-timeout: 30000
      test-while-idle: false
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: false
        #session-stat-max-count:
        #principal-session-name:
        #principal-cookie-name:
        profile-enable: true
      stat-view-servlet: 
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: chenxh
        login-password: chenxh123
        #allow: 127.0.0.1
        deny: 192.168.0.11
      aop-patterns: cn.chenxhcloud.services.*
