logging:
  file: leopard.log
  path: .
spring:
  application:
    name: snow-leopard
  aop:
    proxy-target-class: true
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化连接数量
      initial-size: 2
      #最大并发连接数
      max-active: 8
      #最小空闲连接数
      min-idle: 2
      #指定连接池等待连接返回的最大等待时间，单位毫秒
      max-wait: 10000
      #每隔五分钟检测空闲超过10分钟的连接
      time-between-eviction-runs-millis: 300000 #指定空闲连接检查、废弃连接清理、空闲连接池大小调整之间的操作时间间隔
      min-evictable-idle-time-millis: 600000 #指定一个空闲连接最少空闲多久后可被清除
      #max-evictable-idle-time-millis: 3600000
      #用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1
      validation-query-timeout: 30000
      #建议配置为true，不影响性能，并且保证安全性。 申请连接的时候检测，如果空闲时间大于 time-between-eviction-runs-millis， 执行validation-query检测连接是否有效。
      test-while-idle: true
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: true
      test-on-return: false
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。5.5及以上版本有PSCache，建议开启。
      pool-prepared-statements: true
      #要启用PSCache，必须配置大于0，当大于0时，pool-prepared-statements自动触发修改为true。单个connnection独享一个statement cache，也就是说max-open-prepared-statements是针对单个connection链接的
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      #指定当连接超过废弃超时时间时，是否立刻删除该连接.
      remove-abandoned: true
      #指定连接应该被废弃的时间
      remove-abandoned-timeout: 30
      #remove-abandoned-timeout-millis: 30000
      log-abandoned: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: false
        #session-stat-max-count:
        #principal-session-name:
        #principal-cookie-name:
        profile-enable: true
      stat-view-servlet: 
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: chenxh
        login-password: chenxh123
        #allow: 127.0.0.1
        #deny: 192.168.0.11
      aop-patterns: cn.chenxhcloud.services.*
  output:
    ansi:
      enabled: detect
  batch:
    file-path:
      src: D:/tmp/data/alipay/
      dist: D:/tmp/data/alipay/result/
    job:
      enabled: false
  data:
    mongodb: 
      host: 111.230.233.152
      database: chenxh
      username: chenxh
      password: cxh123
  rabbitmq:
    host: 111.230.233.152
    port: 5673
    username: chenxh
    password: cxh123
    #virtual-host: /
      
