spring:
  application:
    name: chenxh-leopard
  redis:
    host: 111.230.233.152
    port: 6379
  #配置多个数据源
  mydatasources: 
    test:
      url: jdbc:mysql://gz-cdb-e3mogspj.sql.tencentcdb.com:63643/test?characterEncoding=utf8&useSSL=false
      username: root
      password: cxh234mca$
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
    mysql:
      url: jdbc:mysql://gz-cdb-e3mogspj.sql.tencentcdb.com:63643/mysql?characterEncoding=utf8&useSSL=false
      username: root
      password: cxh234mca$
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
server:
  port: 7009
logging:
  level:
    cn:
      chenxhcloud: error