spring:
  application:
    name: chenxh-leopard
  redis:
    host: 127.0.0.1
    port: 6379
  mydatasources: 
    test:
      url: jdbc:mysql://gz-cdb-e3mogspj.sql.tencentcdb.com:63643/test?characterEncoding=utf8&useSSL=false
      username: root
      password: cxh234mca$
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver      
    mysql:      
      url: jdbc:mysql://gz-cdb-e3mogspj.sql.tencentcdb.com:63643/mysql?characterEncoding=utf8&useSSL=false
      username: root
      password: cxh234mca$
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver              
server:
  port: 7001
logging:
  level:
    cn:
      chenxhcloud: debug