spring:
  application:
    name: chenxh-leopard
  redis:
    host: localhost
    port: 6379
  mydatasources: 
    test:
      url: jdbc:mysql://gz-cdb-e3mogspj.sql.tencentcdb.com:63643/test?characterEncoding=utf8&useSSL=false
      username: root
      password: cxh234mca$
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
    cjyun:
      driverClassName: com.mysql.jdbc.Driver
      password: cjyun-TEST
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://rm-wz95c58i9ixyqw206o.mysql.rds.aliyuncs.com:3306/cjyun?characterEncoding=utf8&useSSL=false
      username: cjyun
server:
  port: 7009
logging:
  level:
    cn:
      chenxhcloud: info